animal = input("Enter an animal: ")
color = input("Enter a color: ")
car = input("Enter a car: ")
preposition = input("Enter a preposition: ")
pronoun = input("Enter a pronoun: ")

print("I got the " + animal + " in the back")
print(animal + " tack is attached")
print("Hat is matte " + color)
print("Got the boots that's " + color + " to match")
print("Ridin' on a " + animal + ", ha")
print("You can whip your " + car)
print("I been " + preposition + " the valley")
print( pronoun + " ain't been up off that porch, now")
